name: my_book_list
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  


  cupertino_icons: ^1.0.8
  image_picker: ^1.2.0
  shared_preferences: ^2.5.3
  google_sign_in: ^6.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.4.6
  
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#ffffff" # cor de fundo
  image: lib\recursos\images\my-book-list.png 
  android: true
  

flutter:


  uses-material-design: true

  assets:
    - lib/recursos/json/livros.json
    - lib/recursos/images/
  



  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
